export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    backgroundColor: '#075E54',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 10,
    paddingTop: 50,
  },
  headerButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#A8D08D',
    marginTop: 2,
  },
  postButton: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#fff',
  },
  postButtonDisabled: {
    backgroundColor: 'rgba(255,255,255,0.5)',
  },
  postButtonText: {
    color: '#075E54',
    fontWeight: 'bold',
    fontSize: 14,
  },
  postButtonTextDisabled: {
    color: 'rgba(7,94,84,0.5)',
  },
  mediaSelectionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 20,
    backgroundColor: '#F5F5F5',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  mediaOption: {
    alignItems: 'center',
  },
  mediaIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  mediaIconActive: {
    backgroundColor: '#E8F5E9',
    borderWidth: 2,
    borderColor: '#075E54',
  },
  mediaLabel: {
    fontSize: 12,
    color: '#999',
  },
  mediaLabelActive: {
    color: '#075E54',
    fontWeight: '600',
  },
  content: {
    flex: 1,
  },
  textEditorContainer: {
    paddingBottom: 20,
  },
  textPreview: {
    height: 400,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    position: 'relative',
  },
  textInput: {
    textAlign: 'center',
    width: '100%',
    minHeight: 100,
    maxHeight: 300,
  },
  charCounter: {
    position: 'absolute',
    bottom: 10,
    right: 20,
    fontSize: 12,
  },
  optionsSection: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  optionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666',
    marginBottom: 10,
  },
  colorOption: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  colorOptionSelected: {
    borderColor: '#000',
    transform: [{ scale: 1.1 }],
  },
  rowOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  textColorOption: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
    marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  textColorOptionSelected: {
    borderColor: '#075E54',
  },
  textColorSample: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  fontStyleOption: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    marginRight: 10,
    marginBottom: 10,
  },
  fontStyleOptionSelected: {
    backgroundColor: '#075E54',
    borderColor: '#075E54',
  },
  fontStyleText: {
    fontSize: 14,
    color: '#666',
  },
  fontStyleTextSelected: {
    color: '#fff',
  },
  fontSizeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  fontSizeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E8F5E9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fontSizeSlider: {
    flex: 1,
    height: 4,
    backgroundColor: '#E0E0E0',
    borderRadius: 2,
    marginHorizontal: 15,
  },
  sliderFill: {
    height: '100%',
    backgroundColor: '#075E54',
    borderRadius: 2,
  },
  mediaPreviewContainer: {
    height: 400,
  },
  mediaPreview: {
    flex: 1,
    position: 'relative',
  },
  mediaImage: {
    width: '100%',
    height: '100%',
  },
  removeMediaButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#fff',
    borderRadius: 15,
  },
  captionOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  captionInput: {
    color: '#fff',
    fontSize: 16,
    minHeight: 40,
  },
  privacySection: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666',
    textTransform: 'uppercase',
    marginBottom: 15,
  },
  privacyOption: {
    paddingVertical: 15,
    paddingHorizontal: 15,
    borderRadius: 10,
    backgroundColor: '#F5F5F5',
    marginBottom: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  privacyOptionSelected: {
    backgroundColor: '#E8F5E9',
    borderColor: '#075E54',
  },
  privacyLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  privacyRadio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#999',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    marginTop: 2,
  },
  privacyRadioFill: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#075E54',
  },
  privacyInfo: {
    flex: 1,
  },
  privacyLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  privacyLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    marginLeft: 8,
  },
  privacyDescription: {
    fontSize: 13,
    color: '#999',
    marginLeft: 28,
  },
  durationSection: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 30,
  },
  durationOptions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  durationOption: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#F5F5F5',
    marginHorizontal: 5,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  durationOptionSelected: {
    backgroundColor: '#E8F5E9',
    borderColor: '#075E54',
  },
  durationText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#666',
  },
  durationTextSelected: {
    color: '#075E54',
  },
});
