
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    backgroundColor: '#075E54',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 10,
    paddingTop: 50,
  },
  headerButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  content: {
    flex: 1,
  },
  myStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  myStatusLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  myStatusAvatarContainer: {
    position: 'relative',
    marginRight: 15,
  },
  myStatusAvatar: {
    width: 55,
    height: 55,
    borderRadius: 27.5,
    backgroundColor: '#A8D08D',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addStatusBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#075E54',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  myStatusInfo: {
    flex: 1,
  },
  myStatusTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 4,
  },
  myStatusSubtitle: {
    fontSize: 14,
    color: '#999',
  },
  createStatusButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#075E54',
    justifyContent: 'center',
    alignItems: 'center',
  },
  section: {
    marginBottom: 5,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#999',
    textTransform: 'uppercase',
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#F5F5F5',
  },
  mutedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    paddingRight: 20,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
  },
  statusRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  statusAvatarContainer: {
    position: 'relative',
    marginRight: 15,
  },
  statusAvatarRing: {
    width: 55,
    height: 55,
    borderRadius: 27.5,
    padding: 3,
    borderWidth: 2.5,
  },
  statusAvatarRingUnseen: {
    borderColor: '#075E54',
  },
  statusAvatarRingSeen: {
    borderColor: '#E0E0E0',
  },
  statusPreview: {
    width: '100%',
    height: '100%',
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    padding: 5,
  },
  statusPreviewText: {
    fontSize: 8,
    textAlign: 'center',
    lineHeight: 10,
  },
  statusAvatar: {
    width: '100%',
    height: '100%',
    borderRadius: 25,
    backgroundColor: '#E8F5E9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusAvatarText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#075E54',
  },
  multipleStatusBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#075E54',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  multipleStatusText: {
    fontSize: 10,
    color: '#fff',
    fontWeight: 'bold',
  },
  statusInfo: {
    flex: 1,
  },
  statusName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    marginBottom: 3,
  },
  statusTime: {
    fontSize: 13,
    color: '#999',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyStateTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000',
    marginTop: 20,
    marginBottom: 10,
  },
  emptyStateText: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
  },
  createFirstStatusButton: {
    backgroundColor: '#075E54',
    paddingHorizontal: 25,
    paddingVertical: 12,
    borderRadius: 25,
  },
  createFirstStatusText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  fabContainer: {
    position: 'absolute',
    right: 20,
    bottom: 20,
  },
  fab: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#075E54',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  fabSecondary: {
    marginTop: 10,
    backgroundColor: '#128C7E',
  },
});
