import { StyleSheet } from 'react-native';
// ==================== SHARED STYLES ====================
const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
    },
    header: {
      backgroundColor: '#075E54',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 15,
      paddingVertical: 10,
      paddingTop: 50,
    },
    headerButton: {
      width: 40,
      height: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#fff',
    },
    tabs: {
      flexDirection: 'row',
      backgroundColor: '#F5F5F5',
      borderBottomWidth: 1,
      borderBottomColor: '#E0E0E0',
    },
    tab: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
    },
    activeTab: {
      borderBottomWidth: 2,
      borderBottomColor: '#075E54',
    },
    tabText: {
      fontSize: 13,
      color: '#999',
      marginLeft: 5,
    },
    activeTabText: {
      color: '#075E54',
      fontWeight: '600',
    },
    content: {
      flex: 1,
    },
    // Admin Styles
    analyticsContainer: {
      flexDirection: 'row',
      padding: 15,
      justifyContent: 'space-between',
    },
    analyticsCard: {
      flex: 1,
      backgroundColor: '#F5F5F5',
      padding: 15,
      borderRadius: 10,
      alignItems: 'center',
      marginHorizontal: 5,
    },
    analyticsNumber: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#000',
      marginTop: 8,
      marginBottom: 4,
    },
    analyticsLabel: {
      fontSize: 11,
      color: '#999',
    },
    section: {
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: '#F0F0F0',
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000',
      marginBottom: 12,
    },
    typeContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    typeButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 15,
      paddingVertical: 10,
      borderRadius: 20,
      backgroundColor: '#F5F5F5',
      marginRight: 10,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: '#E0E0E0',
    },
    typeButtonText: {
      fontSize: 13,
      color: '#666',
      marginLeft: 5,
    },
    typeButtonTextActive: {
      color: '#fff',
      fontWeight: '600',
    },
    audienceOption: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      paddingHorizontal: 15,
      borderRadius: 10,
      backgroundColor: '#F5F5F5',
      marginBottom: 8,
      borderWidth: 1,
      borderColor: '#F5F5F5',
    },
    audienceOptionSelected: {
      backgroundColor: '#E8F5E9',
      borderColor: '#075E54',
    },
    audienceLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    radio: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2,
      borderColor: '#999',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    radioFill: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: '#075E54',
    },
    audienceLabel: {
      fontSize: 15,
      color: '#000',
    },
    audienceCount: {
      fontSize: 14,
      color: '#999',
      fontWeight: '600',
    },
    inputContainer: {
      marginBottom: 15,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: '#000',
      marginBottom: 8,
    },
    input: {
      borderWidth: 1,
      borderColor: '#E0E0E0',
      borderRadius: 10,
      paddingHorizontal: 15,
      paddingVertical: 12,
      fontSize: 15,
      color: '#000',
      backgroundColor: '#F5F5F5',
    },
    messageInput: {
      height: 100,
      textAlignVertical: 'top',
    },
    charCount: {
      fontSize: 12,
      color: '#999',
      textAlign: 'right',
      marginTop: 5,
    },
    optionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
    },
    optionInfo: {
      flex: 1,
      marginRight: 15,
    },
    optionLabel: {
      fontSize: 15,
      fontWeight: '600',
      color: '#000',
    },
    optionDescription: {
      fontSize: 13,
      color: '#999',
    },
    uploadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      backgroundColor: '#E8F5E9',
      borderRadius: 10,
    },
    uploadText: {
      fontSize: 14,
      color: '#075E54',
      fontWeight: '600',
      marginLeft: 8,
    },
    actionButtonsContainer: {
      padding: 15,
    },
    sendButton: {
      flexDirection: 'row',
      backgroundColor: '#075E54',
      paddingVertical: 15,
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 10,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    sendButtonDisabled: {
      backgroundColor: '#A8D08D',
      elevation: 0,
    },
    sendButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: 'bold',
      marginLeft: 8,
    },
    scheduleButton: {
      flexDirection: 'row',
      backgroundColor: '#E8F5E9',
      paddingVertical: 15,
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#075E54',
    },
    scheduleButtonText: {
      color: '#075E54',
      fontSize: 14,
      fontWeight: '600',
      marginLeft: 8,
    },
    historyList: {
      padding: 15,
    },
    historyItem: {
      backgroundColor: '#F5F5F5',
      padding: 15,
      borderRadius: 10,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: '#E0E0E0',
    },
    historyHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    historyTypeBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    historyTypeText: {
      color: '#fff',
      fontSize: 11,
      fontWeight: '600',
      textTransform: 'capitalize',
    },
    historyTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000',
      marginBottom: 5,
    },
    historyMessage: {
      fontSize: 14,
      color: '#666',
      marginBottom: 10,
    },
    historyStats: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    historyStat: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    historyStatText: {
      fontSize: 12,
      color: '#666',
      marginLeft: 5,
    },
    historyTime: {
      fontSize: 12,
      color: '#999',
    },
    analyticsDetailed: {
      padding: 15,
    },
    analyticsTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#000',
      marginBottom: 15,
    },
    metricsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginBottom: 20,
    },
    metricCard: {
      width: '48%',
      backgroundColor: '#F5F5F5',
      padding: 15,
      borderRadius: 10,
      alignItems: 'center',
      margin: '1%',
    },
    metricNumber: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#000',
      marginBottom: 5,
    },
    metricLabel: {
      fontSize: 12,
      color: '#999',
    },
    chartContainer: {
      backgroundColor: '#F5F5F5',
      padding: 15,
      borderRadius: 10,
    },
    chartTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000',
      marginBottom: 15,
    },
    chartRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    chartInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      width: 100,
    },
    chartDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      marginRight: 8,
    },
    chartLabel: {
      fontSize: 13,
      color: '#666',
    },
    chartBarContainer: {
      flex: 1,
      height: 20,
      backgroundColor: '#E0E0E0',
      borderRadius: 10,
      marginHorizontal: 10,
      overflow: 'hidden',
    },
    chartBar: {
      height: '100%',
      borderRadius: 10,
    },
    chartValue: {
      fontSize: 13,
      color: '#666',
      width: 30,
      textAlign: 'right',
    },
    emptyState: {
      alignItems: 'center',
      paddingVertical: 40,
    },
    emptyStateText: {
      fontSize: 16,
      color: '#999',
      marginTop: 10,
    },
    // Modal Styles
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      padding: 20,
    },
    userModal: {
      backgroundColor: '#fff',
      borderRadius: 20,
      maxHeight: '70%',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      borderBottomWidth: 1,
      borderBottomColor: '#F0F0F0',
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#000',
    },
    selectedCount: {
      fontSize: 14,
      color: '#999',
      paddingHorizontal: 20,
      paddingVertical: 10,
    },
    userSelectItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#F0F0F0',
    },
    userSelectInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    userSelectAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#E8F5E9',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    userSelectAvatarText: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#075E54',
    },
    userSelectName: {
      fontSize: 15,
      fontWeight: '600',
      color: '#000',
    },
    userSelectEmail: {
      fontSize: 12,
      color: '#999',
    },
    checkbox: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: '#E0E0E0',
      justifyContent: 'center',
      alignItems: 'center',
    },
    checkboxSelected: {
      backgroundColor: '#075E54',
      borderColor: '#075E54',
    },
    doneButton: {
      backgroundColor: '#075E54',
      paddingVertical: 15,
      margin: 20,
      borderRadius: 10,
      alignItems: 'center',
    },
    doneButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: 'bold',
    },
    // Support Styles
    supportSection: {
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: '#F0F0F0',
    },
    supportSectionTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#000',
      marginBottom: 15,
    },
    emailCard: {
      backgroundColor: '#E8F5E9',
      padding: 20,
      borderRadius: 15,
      alignItems: 'center',
      borderWidth: 2,
      borderColor: '#075E54',
      borderStyle: 'dashed',
    },
    emailTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#000',
      marginTop: 10,
      marginBottom: 5,
    },
    emailAddress: {
      fontSize: 16,
      color: '#075E54',
      fontWeight: '600',
      marginBottom: 15,
    },
    emailButton: {
      flexDirection: 'row',
      backgroundColor: '#075E54',
      paddingHorizontal: 25,
      paddingVertical: 12,
      borderRadius: 25,
      alignItems: 'center',
    },
    emailButtonText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: 'bold',
      marginLeft: 8,
    },
    categoryChip: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 15,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: '#F5F5F5',
      marginRight: 10,
      borderWidth: 1,
      borderColor: '#E0E0E0',
    },
    categoryChipActive: {
      backgroundColor: '#075E54',
      borderColor: '#075E54',
    },
    categoryChipText: {
      fontSize: 13,
      color: '#075E54',
      marginLeft: 5,
    },
    categoryChipTextActive: {
      color: '#fff',
    },
    submitButton: {
      flexDirection: 'row',
      backgroundColor: '#075E54',
      paddingVertical: 15,
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    submitButtonDisabled: {
      backgroundColor: '#A8D08D',
      elevation: 0,
    },
    submitButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: 'bold',
      marginLeft: 8,
    },
    quickAction: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 15,
      paddingHorizontal: 15,
      backgroundColor: '#F5F5F5',
      borderRadius: 10,
      marginBottom: 10,
    },
    quickActionInfo: {
      flex: 1,
      marginLeft: 15,
    },
    quickActionTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: '#000',
    },
    quickActionDescription: {
      fontSize: 13,
      color: '#999',
      marginTop: 2,
    },
    ticketItem: {
      backgroundColor: '#F5F5F5',
      padding: 15,
      borderRadius: 10,
      marginBottom: 10,
    },
    ticketHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    ticketSubject: {
      fontSize: 15,
      fontWeight: '600',
      color: '#000',
      flex: 1,
    },
    ticketStatus: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    statusOpen: {
      backgroundColor: '#FFF3E0',
    },
    statusResolved: {
      backgroundColor: '#E8F5E9',
    },
    ticketStatusText: {
      fontSize: 11,
      fontWeight: '600',
      textTransform: 'capitalize',
    },
    statusOpenText: {
      color: '#F57C00',
    },
    statusResolvedText: {
      color: '#4CAF50',
    },
    ticketMeta: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    ticketDate: {
      fontSize: 12,
      color: '#999',
    },
    ticketMessages: {
      fontSize: 12,
      color: '#999',
    },
    faqContainer: {
      padding: 15,
    },
    faqTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#000',
      marginBottom: 20,
    },
    faqItem: {
      backgroundColor: '#F5F5F5',
      padding: 15,
      borderRadius: 10,
      marginBottom: 15,
    },
    faqQuestionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    faqQuestion: {
      fontSize: 15,
      fontWeight: '600',
      color: '#000',
      marginLeft: 10,
      flex: 1,
    },
    faqAnswer: {
      fontSize: 14,
      color: '#666',
      lineHeight: 20,
      marginLeft: 30,
    },
    reportContainer: {
      padding: 15,
    },
    reportTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#000',
      marginBottom: 10,
    },
    reportDescription: {
      fontSize: 14,
      color: '#666',
      marginBottom: 20,
    },
    reportOption: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 15,
      paddingHorizontal: 15,
      backgroundColor: '#F5F5F5',
      borderRadius: 10,
      marginBottom: 10,
    },
    reportOptionText: {
      flex: 1,
      fontSize: 15,
      fontWeight: '600',
      color: '#000',
      marginLeft: 15,
    },
    emergencyButton: {
      flexDirection: 'row',
      backgroundColor: '#F44336',
      paddingVertical: 15,
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 20,
    },
    emergencyText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: 'bold',
      marginLeft: 8,
    },
});
  
export default styles